<?php
return
[
    'options' =>[
    'RESPONSE_OK' => 200,
    'RESPONSE_CREATED' => 201,
    'RESPONSE_NO_CONTENT' => 204,
    'RESPONSE_PARTIAL_CONTENT' => 206,
    'RESPONSE_BAD_REQUEST' => 400,
    'RESPONSE_UNAUTORIZED' => 401,
    'RESPONSE_FORBIDEN' => 403,
    'RESPONSE_NOT_FOUND' => 404,
    'RESPONSE_INTERNAL_ERROR' => 500,
    'RESPONSE_UNVAILABLE' => 503,
    ]
    ];